version: '3'
services:
    app:
        build:
            context: ./app
            args:
                - image=${APP_IMAGE}
        container_name: ${APP_CONTAINER_NAME}
        user: node
        restart: always
        volumes:
            - ./app:/src/app
        ports:
            - '${APP_PORT}:3000'
        environment:
            - TZ=Europe/Paris
networks:
    default:
        external:
            name: main
