version: '3'
services:
    app:
        build:
            context: ./app
            args:
                - image=${APP_IMAGE}
        container_name: ${APP_CONTAINER_NAME}
        restart: always
        volumes:
            - ./app/app.ts:/src/app.ts
            - ./app/controller:/src/controller
            - ./app/middleware:/src/middleware
            - ./app/tsconfig.json:/src/tsconfig.json
        ports:
            - '${APP_PORT}:3000'
        environment:
            - TZ=Europe/Paris
networks:
    default:
        external:
            name: main
